### ISSUE TITLE
Report ERROR

### ISSUE THREAD

**Issue by Chtidino** [Cryotheus/nzombies_progress_bar#2]
[ERROR] lua/autorun/client/nz_progress_bar.lua:147: attempt to call global 'create_font' (a nil value)
  1. register_font - lua/autorun/client/nz_progress_bar.lua:147
   2. set_font - lua/autorun/client/nz_progress_bar.lua:154
    3. unknown - lua/autorun/client/nz_progress_bar.lua:159

**Comment by Cryotheus** [comment]
Thank you for all your reports.
