### ISSUE TITLE
Repport ERROR

### ISSUE THREAD

**Issue by Chtidino** [Cryotheus/nzombies_progress_bar#3]
This appear when player finish join server

[nZombies Round Progress Bar] lua/autorun/server/nz_progress_bar.lua:62: bad argument #1 to 'Send' (Entity expected, got number)
  1. Send - [C]:-1
   2. func - lua/autorun/server/nz_progress_bar.lua:62
    3. unknown - lua/includes/extensions/net.lua:33

**Comment by Cryotheus** [comment]
Fixed it, the updated version is now on GitHub.  
Thank you for your report.
